
all: slo rla sre rra

slo:
	mads -l -o:slo_asoa.bin slo_asoa.asm
	mads -d:ATARI=1 -o:slo_asoa.xex slo_asoa.asm
	mads -l -o:slo_asoax.bin slo_asoax.asm
	mads -d:ATARI=1 -o:slo_asoax.xex slo_asoax.asm
	mads -l -o:slo_asoay.bin slo_asoay.asm
	mads -d:ATARI=1 -o:slo_asoay.xex slo_asoay.asm
	mads -l -o:slo_asoix.bin slo_asoix.asm
	mads -d:ATARI=1 -o:slo_asoix.xex slo_asoix.asm
	mads -l -o:slo_asoiy.bin slo_asoiy.asm
	mads -d:ATARI=1 -o:slo_asoiy.xex slo_asoiy.asm
	mads -l -o:slo_asoz.bin slo_asoz.asm
	mads -d:ATARI=1 -o:slo_asoz.xex slo_asoz.asm
	mads -l -o:slo_asozx.bin slo_asozx.asm
	mads -d:ATARI=1 -o:slo_asozx.xex slo_asozx.asm

rla:
	mads -l -o:rlaa.bin rlaa.asm
	mads -d:ATARI=1 -o:rlaa.xex rlaa.asm
	mads -l -o:rlaax.bin rlaax.asm
	mads -d:ATARI=1 -o:rlaax.xex rlaax.asm
	mads -l -o:rlaay.bin rlaay.asm
	mads -d:ATARI=1 -o:rlaay.xex rlaay.asm
	mads -l -o:rlaix.bin rlaix.asm
	mads -d:ATARI=1 -o:rlaix.xex rlaix.asm
	mads -l -o:rlaiy.bin rlaiy.asm
	mads -d:ATARI=1 -o:rlaiy.xex rlaiy.asm
	mads -l -o:rlaz.bin rlaz.asm
	mads -d:ATARI=1 -o:rlaz.xex rlaz.asm
	mads -l -o:rlazx.bin rlazx.asm
	mads -d:ATARI=1 -o:rlazx.xex rlazx.asm

sre:
	mads -l -o:sre_lsea.bin sre_lsea.asm
	mads -d:ATARI=1 -o:sre_lsea.xex sre_lsea.asm
	mads -l -o:sre_lseax.bin sre_lseax.asm
	mads -d:ATARI=1 -o:sre_lseax.xex sre_lseax.asm
	mads -l -o:sre_lseay.bin sre_lseay.asm
	mads -d:ATARI=1 -o:sre_lseay.xex sre_lseay.asm
	mads -l -o:sre_lseix.bin sre_lseix.asm
	mads -d:ATARI=1 -o:sre_lseix.xex sre_lseix.asm
	mads -l -o:sre_lseiy.bin sre_lseiy.asm
	mads -d:ATARI=1 -o:sre_lseiy.xex sre_lseiy.asm
	mads -l -o:sre_lsez.bin sre_lsez.asm
	mads -d:ATARI=1 -o:sre_lsez.xex sre_lsez.asm
	mads -l -o:sre_lsezx.bin sre_lsezx.asm
	mads -d:ATARI=1 -o:sre_lsezx.xex sre_lsezx.asm

rra:
	mads -l -o:rraa.bin rraa.asm
	mads -d:ATARI=1 -o:rraa.xex rraa.asm
	mads -l -o:rraax.bin rraax.asm
	mads -d:ATARI=1 -o:rraax.xex rraax.asm
	mads -l -o:rraay.bin rraay.asm
	mads -d:ATARI=1 -o:rraay.xex rraay.asm
	mads -l -o:rraix.bin rraix.asm
	mads -d:ATARI=1 -o:rraix.xex rraix.asm
	mads -l -o:rraiy.bin rraiy.asm
	mads -d:ATARI=1 -o:rraiy.xex rraiy.asm
	mads -l -o:rraz.bin rraz.asm
	mads -d:ATARI=1 -o:rraz.xex rraz.asm
	mads -l -o:rrazx.bin rrazx.asm
	mads -d:ATARI=1 -o:rrazx.xex rrazx.asm

clean:
	rm -f *~ *.bin *.xex *.lst
