
all: slo rla sre rra sax lax dcp isc anc alr

slo:
	mads -l -o:slo_asoa.bin slo_asoa.asm
	mads -d:ATARI=1 -o:slo_asoa.xex slo_asoa.asm
	mads -l -o:slo_asoax.bin slo_asoax.asm
	mads -d:ATARI=1 -o:slo_asoax.xex slo_asoax.asm
	mads -l -o:slo_asoay.bin slo_asoay.asm
	mads -d:ATARI=1 -o:slo_asoay.xex slo_asoay.asm
	mads -l -o:slo_asoix.bin slo_asoix.asm
	mads -d:ATARI=1 -o:slo_asoix.xex slo_asoix.asm
	mads -l -o:slo_asoiy.bin slo_asoiy.asm
	mads -d:ATARI=1 -o:slo_asoiy.xex slo_asoiy.asm
	mads -l -o:slo_asoz.bin slo_asoz.asm
	mads -d:ATARI=1 -o:slo_asoz.xex slo_asoz.asm
	mads -l -o:slo_asozx.bin slo_asozx.asm
	mads -d:ATARI=1 -o:slo_asozx.xex slo_asozx.asm

rla:
	mads -l -o:rlaa.bin rlaa.asm
	mads -d:ATARI=1 -o:rlaa.xex rlaa.asm
	mads -l -o:rlaax.bin rlaax.asm
	mads -d:ATARI=1 -o:rlaax.xex rlaax.asm
	mads -l -o:rlaay.bin rlaay.asm
	mads -d:ATARI=1 -o:rlaay.xex rlaay.asm
	mads -l -o:rlaix.bin rlaix.asm
	mads -d:ATARI=1 -o:rlaix.xex rlaix.asm
	mads -l -o:rlaiy.bin rlaiy.asm
	mads -d:ATARI=1 -o:rlaiy.xex rlaiy.asm
	mads -l -o:rlaz.bin rlaz.asm
	mads -d:ATARI=1 -o:rlaz.xex rlaz.asm
	mads -l -o:rlazx.bin rlazx.asm
	mads -d:ATARI=1 -o:rlazx.xex rlazx.asm

sre:
	mads -l -o:sre_lsea.bin sre_lsea.asm
	mads -d:ATARI=1 -o:sre_lsea.xex sre_lsea.asm
	mads -l -o:sre_lseax.bin sre_lseax.asm
	mads -d:ATARI=1 -o:sre_lseax.xex sre_lseax.asm
	mads -l -o:sre_lseay.bin sre_lseay.asm
	mads -d:ATARI=1 -o:sre_lseay.xex sre_lseay.asm
	mads -l -o:sre_lseix.bin sre_lseix.asm
	mads -d:ATARI=1 -o:sre_lseix.xex sre_lseix.asm
	mads -l -o:sre_lseiy.bin sre_lseiy.asm
	mads -d:ATARI=1 -o:sre_lseiy.xex sre_lseiy.asm
	mads -l -o:sre_lsez.bin sre_lsez.asm
	mads -d:ATARI=1 -o:sre_lsez.xex sre_lsez.asm
	mads -l -o:sre_lsezx.bin sre_lsezx.asm
	mads -d:ATARI=1 -o:sre_lsezx.xex sre_lsezx.asm

rra:
	mads -l -o:rraa.bin rraa.asm
	mads -d:ATARI=1 -o:rraa.xex rraa.asm
	mads -l -o:rraax.bin rraax.asm
	mads -d:ATARI=1 -o:rraax.xex rraax.asm
	mads -l -o:rraay.bin rraay.asm
	mads -d:ATARI=1 -o:rraay.xex rraay.asm
	mads -l -o:rraix.bin rraix.asm
	mads -d:ATARI=1 -o:rraix.xex rraix.asm
	mads -l -o:rraiy.bin rraiy.asm
	mads -d:ATARI=1 -o:rraiy.xex rraiy.asm
	mads -l -o:rraz.bin rraz.asm
	mads -d:ATARI=1 -o:rraz.xex rraz.asm
	mads -l -o:rrazx.bin rrazx.asm
	mads -d:ATARI=1 -o:rrazx.xex rrazx.asm

sax:
	mads -l -o:sax_axsa.bin sax_axsa.asm
	mads -d:ATARI=1 -o:sax_axsa.xex sax_axsa.asm
	mads -l -o:sax_axsix.bin sax_axsix.asm
	mads -d:ATARI=1 -o:sax_axsix.xex sax_axsix.asm
	mads -l -o:sax_axsz.bin sax_axsz.asm
	mads -d:ATARI=1 -o:sax_axsz.xex sax_axsz.asm
	mads -l -o:sax_axszy.bin sax_axszy.asm
	mads -d:ATARI=1 -o:sax_axszy.xex sax_axszy.asm

lax:
	mads -l -o:laxa.bin laxa.asm
	mads -d:ATARI=1 -o:laxa.xex laxa.asm
	mads -l -o:laxay.bin laxay.asm
	mads -d:ATARI=1 -o:laxay.xex laxay.asm
	mads -l -o:laxix.bin laxix.asm
	mads -d:ATARI=1 -o:laxix.xex laxix.asm
	mads -l -o:laxiy.bin laxiy.asm
	mads -d:ATARI=1 -o:laxiy.xex laxiy.asm
	mads -l -o:laxz.bin laxz.asm
	mads -d:ATARI=1 -o:laxz.xex laxz.asm
	mads -l -o:laxzy.bin laxzy.asm
	mads -d:ATARI=1 -o:laxzy.xex laxzy.asm

dcp:
	mads -l -o:dcp_dcma.bin dcp_dcma.asm
	mads -d:ATARI=1 -o:dcp_dcma.xex dcp_dcma.asm
	mads -l -o:dcp_dcmax.bin dcp_dcmax.asm
	mads -d:ATARI=1 -o:dcp_dcmax.xex dcp_dcmax.asm
	mads -l -o:dcp_dcmay.bin dcp_dcmay.asm
	mads -d:ATARI=1 -o:dcp_dcmay.xex dcp_dcmay.asm
	mads -l -o:dcp_dcmix.bin dcp_dcmix.asm
	mads -d:ATARI=1 -o:dcp_dcmix.xex dcp_dcmix.asm
	mads -l -o:dcp_dcmiy.bin dcp_dcmiy.asm
	mads -d:ATARI=1 -o:dcp_dcmiy.xex dcp_dcmiy.asm
	mads -l -o:dcp_dcmz.bin dcp_dcmz.asm
	mads -d:ATARI=1 -o:dcp_dcmz.xex dcp_dcmz.asm
	mads -l -o:dcp_dcmzx.bin dcp_dcmzx.asm
	mads -d:ATARI=1 -o:dcp_dcmzx.xex dcp_dcmzx.asm

isc:
	mads -l -o:isc_insa.bin isc_insa.asm
	mads -d:ATARI=1 -o:isc_insa.xex isc_insa.asm
	mads -l -o:isc_insax.bin isc_insax.asm
	mads -d:ATARI=1 -o:isc_insax.xex isc_insax.asm
	mads -l -o:isc_insay.bin isc_insay.asm
	mads -d:ATARI=1 -o:isc_insay.xex isc_insay.asm
	mads -l -o:isc_insix.bin isc_insix.asm
	mads -d:ATARI=1 -o:isc_insix.xex isc_insix.asm
	mads -l -o:isc_insiy.bin isc_insiy.asm
	mads -d:ATARI=1 -o:isc_insiy.xex isc_insiy.asm
	mads -l -o:isc_insz.bin isc_insz.asm
	mads -d:ATARI=1 -o:isc_insz.xex isc_insz.asm
	mads -l -o:isc_inszx.bin isc_inszx.asm
	mads -d:ATARI=1 -o:isc_inszx.xex isc_inszx.asm

anc:
	mads -l -o:ancb.bin ancb.asm
	mads -d:ATARI=1 -o:ancb.xex ancb.asm

alr:
	mads -l -o:alrb.bin alrb.asm
	mads -d:ATARI=1 -o:alrb.xex alrb.asm

clean:
	rm -f *~ *.bin *.xex *.lst
